### ISSUE TITLE
Kod

### ISSUE THREAD

**Issue by JuliaSivartsson** [rk222ev/1dv450-Registering-rk222ev-client#1]
Koden ser snygg och prydlig ut. Tydliga instruktioner i readme-filen, dock fick jag inte det att fungera lokalt men det kan vara något med min dator, instruktioner finns i alla fall i readme-filen. Jag valde att dra in det i cloud9 istället för att studera koden.

Det var inga problem att hitta i mappstrukturen utan den är upplagd på ett bra sätt tycker jag.

De olika kontrollerna är bra utbrutna så att de inte blir för stora och de är även tydliga i sin uppgift. Factory används för CRUD funktionaliteten.

Bra att API-key och SERVERURL sätts som konstanter i applikationen, de var även lätta att hitta ifall man skulle använda sig av ett annat api och då behöva ändra dem.

In- och utloggning fungerar utan problem tycker jag.

**Comment by rk222ev** [comment]
Hmm, tråkigt att det inte fungerade lokalt. Har testkört på två datorer här hemma och stött på några problem. Väljer tillsvidare att skylla på din dator :P 

Tack för granskningen.
