### ISSUE TITLE
Gränssnitt och funktionalitet

### ISSUE THREAD

**Issue by JuliaSivartsson** [rk222ev/1dv450-Registering-rk222ev-client#2]
Aktivt menyval byts inte när man trycker i menyn utan det är alltid "Home" som är aktivt, liten detalj bara.

Det kunde vara trevligt att få upp en lista eller tabell på alla event när man inte är inloggad, nu måste man leta efter dem på kartan så om man inte vet vart ett event ligger måste man trycka sig fram för att hitta den man letar efter.

Det fungerar bra att både skapa och redigera evenemang. Det går endast att göra detta på de egna användarna vilket är som det ska vara.
Dock kan jag inte redigera koordinater för ett event, jag kan ändra i redigeringsformuläret men när jag väl sparat så är de återställda till vad de var tidigare. 

Man kan även klicka i vilken tagg (eller vilka taggar) man vill filtrera evenemangen efter i kartvyn.

Flashmeddelanden visas vid uppdatering osv. vilket är bra.

Snyggt att det inte ens går att posta formuläret för nytt event om inte alla fält är ifyllda.

En fördel kunde varit att få se alla taggar som redan finns i systemet när man skapar ett nytt event, så får man lite inspiration och andra kanske lättare hittar ens event.

En liten detalj kan vara att ha en confirm-ruta eller liknande vid radering, det är lätt att klicka fel.

När man redigerar sitt event så är titeln "Add new event", kunde vara tydligare med "Edit event" eller något liknande.

**Comment by rk222ev** [comment]
Kan inte annat än håll med i det du tar upp.
Får definitivt kolla på varför koordinaterna inte uppdaterar. 

Resterande punkter är sådant jag gärna åtgärdat, men av olika anledningar tyvärr inte hunnit med.

Återkommer med uppdateringar angående eventuella ändringar.

**Comment by rk222ev** [comment]
Tog bort den statiska active klassen på home länken i menyn.
Visar inte längre lng, lat när man editerar events. (Tänkte mig att man får ta bort eventet och skapa ett nytt  om man flyttar så finns inte implementerat på backend).

Hade egentligen föredragit andra lösningar men får nog dessvärre nöja mig med projektet i det skick det befinner sig i.

Tack för granskning och många bra förslag på förbättringar.
