### ISSUE TITLE
Övrigt

### ISSUE THREAD

**Issue by JuliaSivartsson** [rk222ev/1dv450-Registering-rk222ev-client#3]
Jag har letat lite men hittar inget 'custom directive', det kan absolut vara så att jag har missat det, i så fall är det bara till att ignorera det här, annars vore det bra att ta en titt på och implementera något.
Information kan hittas här: https://docs.angularjs.org/guide/directive

I övrigt verkar alla krav vara uppfyllda :)

**Comment by rk222ev** [comment]
Custom directives borde finnas [här](https://github.com/rk222ev/1dv450-Registering-rk222ev-client/tree/master/app/scripts/directives) för jag har väl inte missförstått vad ett custom directive är?

**Comment by JuliaSivartsson** [comment]
Ja men absolut! Slarvigt av mig att missa det!
